version: '3.7'

services:
  db:
    image: mysql:8
    ports:
      - "${DB_PORT:-3331}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-abcd1234}
      MYSQL_DATABASE: ${DB_NAME:-chatbot}
    networks:
      - chatbot
    volumes:
      - chatbot_db:/usr/share/nginx/html:ro

networks:
  chatbot:
    driver: bridge

volumes:
  chatbot_db: