const AUDIOS: {
  [key in string]: string[];
} = {
  CHUUNAS: [
    'tomar vicvaporube chunas.wav',
    'AAAI MDS CHUNAS.wav',
    'eu to tiltado chunas.wav',
    'ngm ta de hack chunas.wav',
    'ja to tiltado chunas.wav',
    'esses caras eh gado chunas.wav',
    'cara chato chunas.wav',
    'assinar é meu cu chunas.wav',
    'krl pedro chunas.wav',
    'esqueceu q sou gado chunas.wav',
    'ngm vai rir agora chunas.wav',
    'esse cara impossivel chunas.wav',
    'chunas tiltado.wav',
    'gadar chunas.wav',
    'calma krl chunas.wav',
    'sou gado chunas.wav',
    'vai ficar dando risada aí chunas.wav',
    'WhatsApp Ptt 2019-06-09 at 14.43.28.ogg',
    'os caras fica de cu doce chunas.wav',
    'perder ou ganhar.wav',
    'joao eh um pnc.wav',
    'tiltei chunas.wav',
    'nunca duvidei chunas.wav',
    'explicacao chunas.wav',
    'chunas audio german.wav',
    'cu trincado chunas.mp3',
    'capitao chunas.mp3',
    'me poupe chunas.mp3',
    'eh um time chunas.mp3',
    'chunas exposed.mp3',
    'desanimo chunas.mp3',
    'chunas cantando 2.mp3',
    'chunas gadando.mp3',
    'ãh chunas.mp3',
    'calma gnt chunas.mp3',
    'farpas ticole chunas.mp3',
    'audio chato chunas.mp3',
    'entregar a partida chunas.mp3',
    'audio legal chunas.mp3',
    'cantando chunas.mp3',
    'mds para chunas.mp3',
    'psicologico chunas.mp3',
    'mto tiltada chunas.mp3',
    'hmm chunas.mp3',
    'tosse chunas.mp3',
    'kd chuva de fé chunas.mp3',
    'joga tiltando chunas.mp3',
    'flando q ia dar ruim chunas.mp3',
    'nice marllindo chunas.mp3',
    'n eh pra mim chunas.mp3',
    'sua vo joga bingo chunas.mp3',
    'ain chunas.mp3',
    'vai dormir chunas.mp3',
    'acorda fi chunas.mp3',
    'ai chunas.mp3',
    'mariu bebum chunas.mp3',
    'qro me redimir chunas.mp3',
    'lambe meu pau chunas.mp3',
    'n qro mais jogar chunas.mp3',
    'maluco fdp chunas.mp3',
    'n da n chunas.mp3',
    'jogar sozinho chunas.mp3',
    'vem fdp chunas.mp3',
    'chupa meu cu chunas.mp3',
    'carai chunas.mp3',
    'vcs sabem chunas.mp3',
    'bucetol chunas.mp3',
    'nao paula chunas.mp3',
    'vsf chunas.mp3',
    'coringa chunas.mp3',
    'irma smoq chunas.mp3',
    'n entendo chunas.mp3',
    'desculpa chunas.mp3',
    'lisa nomade chunas.mp3',
    'qm falo chunas.mp3',
    'conselhos chunas.mp3',
    'n eh aqui n chunas.mp3',
    'narnia chunas.mp3',
    'chupa dedao chunas.mp3',
    'era audio chunas.mp3',
    'arriscar chunas.mp3',
    'essa musica chunas.mp3',
    'calma chunas.mp3',
    'maluco idiota chunas.mp3',
    'sair sono chunas.mp3',
    'tirei pra lazer chunas.mp3',
    'sdds da lisa chunas.mp3',
    'PAH spam 2 chunas.mp3',
    'tdo audio chunas.mp3',
    'audio coragem chunas.mp3',
    'pah spam chunas.mp3',
    'qm mando esse audio chunas.mp3',
    'pensa q taonde chunas.mp3',
    'gadando homem chunas.mp3',
    'qlqr audio chunas.mp3',
    'PAH chunas.mp3',
    'n participava chunas.mp3',
    'mto dinheiro chunas.mp3',
    'maldade chunas.mp3',
    'ai chessus chunas.mp3',
    'vo com medo chunas.mp3',
    'capaz chunas.mp3',
    'medo encontrar lisa chunas.mp3',
    'toma remedio chunas.mp3',
    'vcs n presta chunas.mp3',
    'iron estudar chunas.mp3',
    'n vai estuprar chunas.mp3',
    'buguei chunas.mp3',
    'vo te buscar chunas.mp3',
    'mete o loco chunas.mp3',
    'brigada com ele chunas.mp3',
    'n entenderam chunas.mp3',
    'como assim chunas.mp3',
    'bença chunas.mp3',
    'joao vc eh foda.mp3',
    'carai borracha chunas.mp3',
  ],
  Smoke: [
    'muito troll smoke.wav',
    'AT-cm_458420581.mp4',
    'bora clicar mariu smoke.wav',
    'bora bora smoke.wav',
    'merda voltando smoke.wav',
    'tao tiltado smoke.wav',
    'que nojo smoke.wav',
    'nossa senhora smoke.wav',
    'vai vai vai smoke.mp3',
    'n vou parar n smoke.mp3',
    'nego n cansa smoke.mp3',
    'arroto smoke.mp3',
    'pega pega smoke.mp3',
    'mlk pe fedido smoke.mp3',
    'blz, blz smoke.mp3',
    'bando de escroto smoke.mp3',
    'cantando smoke.mp3',
    'fedando e quita smoke.mp3',
    'ja era smoke.mp3',
    'vtnc smoke.mp3',
    'famous tapetao smoke.mp3',
    'igual bot smoke.mp3',
    'klabok smoke.mp3',
    'audio retard smoke.mp3',
    'vamo trolla smoq.mp3',
    'iron remedio smoq.mp3',
    'padre rezar smoq.mp3',
    'iron fazer tdo smoq.mp3',
    'mantesso2k19 smoq.mp3',
    'pau duro smoq.mp3',
    'acho q deu ruim smoq.mp3',
    'palhaço smoq.mp3',
    'n fla cmg smoke.mp3',
    'to tiltado smoq.mp3',
    'flw smoq 3.mp3',
    'flw smoq.mp3',
    'oq ia falar smoq.mp3',
    'sindro de mariu smoq.mp3',
    'flw smoq 2.mp3',
    'amigo iron smoq.mp3',
    'image se namorar smoq.mp3',
    'qisso mariu smoq.mp3',
    'ta maluco smoq.mp3',
    'mariu retardad smoq.mp3',
    'oxi smoq.mp3',
    'ocupado smoq.mp3',
    'to doente smoq.mp3',
    'tnc pedro smoq.mp3',
    'ata smoq.mp3',
    'q retardado smoq.mp3',
    'nunca fui smoq.mp3',
    'mds po smoq.mp3',
    'se fudeu smoke.mp3',
    'até esqueci smoq.mp3',
    'se comprometeu smoke.mp3',
    'smoq baitado.mp3',
    'rulado smoq.mp3',
    'q risada é essa smoq.mp3',
    'smoke cantando 2.mp3',
    'famosa zika smoq.mp3',
  ],
  Weberson: [
    'mal educado weberson.mp3',
    'pedro calcinha weberson.mp3',
    'manda aqui weberson.mp3',
    'klabok weberson.mp3',
    'botando moral weberson.mp3',
    'weberson.mp3',
  ],
  Gouki: [
    'regressiva gouki.mp3',
    'se vai morre gouki.mp3',
    'arrependi de chamar gouki.mp3',
    'cagando andando gouki.mp3',
    'farpas reizao e gouki.mp3',
    'ta fedendoo gouki.mp3',
    'cheiro ruim gouki.mp3',
    'ta podre gouki.mp3',
    'fedor gouki.mp3',
    'para chico gouki.mp3',
    'ah velho gouki.mp3',
    'que lixo gouki.mp3',
    'sorteando rp gouki.mp3',
    'espera gouki.mp3',
    'gorn preto gouki.mp3',
    'cara do mar gouki.mp3',
    'tchutchuca gouki.mp3',
    'jogo todo dia gouki.mp3',
    'mulherzinha gouki.mp3',
    'premium muie gouki.mp3',
    'coisa linda gouki.mp3',
    'vergonha gouki.mp3',
    'entendendo gouki.mp3',
    'explicacao gouki.mp3',
    'kika gouki.mp3',
    'gorn muie gouki.mp3',
    'eh memo gouki.mp3',
    'abestado gouki.mp3',
    'gg izi gouki.mp3',
    'joao afundando gouki.mp3',
    'n consigo gouki.mp3',
    'noçao de jogo gouki.mp3',
    'boa pessoa gouki.mp3',
    'blz gouki.mp3',
    'mae gearth gouki.mp3',
    'falar da mae gouki.mp3',
    'auauau gouki.mp3',
    'culpa tdos gouki.mp3',
    'ah gouki.mp3',
    'flw gouki.mp3',
    'morre facil gouki.mp3',
    'vtnc gouki.mp3',
    'sem educacao gorn gouki.mp3',
    'n entendi gouki.mp3',
    'sem cultura gouki.mp3',
    'vc eh vidaloca gouki.mp3',
    'claro q eh gouki.mp3',
    'vc mto zuero gouki.mp3',
    'sarrando gouki.mp3',
    'oi gouki.mp3',
    'tudo piranha gouki.mp3',
    'jaine gouki.mp3',
    'os caras tem medo gouki.mp3',
    'facil perder gouki.mp3',
    'espera 2 gouki.mp3',
    'vai jogar n gouki.mp3',
    'q fedor completo gouki.mp3',
    'tantan gouki.mp3',
    'rage severus gouki.mp3',
    'vou entrar gouki.mp3',
    'som do sarrando gouki.mp3',
    'marina banir gouki.mp3',
    'explicacao rage gouki.mp3',
    'tb ja fiz gouki.mp3',
    'olha esse gorn gouki.mp3',
    'standup gouki.mp3',
    'funkeiro gouki.mp3',
    'auaua extended gouki.mp3',
    'sua mae gouki.mp3',
    'aquela foi op gouki.mp3',
    'memoria gouki.mp3',
    'jogar com sua mae gouki.mp3',
    'brasileiro gouki.mp3',
    'ta onde gouki.mp3',
    'desculpa gouki.mp3',
    'tomar banho gouki.mp3',
    'haha gouki.mp3',
    'rei sarrando gouki.mp3',
    'ceu tem agua gouki.mp3',
    'oxi gouki.mp3',
    'convida ai gouki.mp3',
    'boa sorte gouki.mp3',
    'tanto faz gouki.mp3',
    'matar ngm gouki.mp3',
    'vo desconta gouki.mp3',
    'sua mae 2 gouki.mp3',
  ],
  TICOLÉ: [
    'carioca errado lisa.mp3',
    'oi lisa.wav',
    '6 qrem me foder lisa.wav',
    'eu sou feliz lisa.wav',
    'se fudeu gadao lisa.wav',
    'pode ir dormir lisa.wav',
    'tchau lisa.wav',
    'joao eh doente lisa.wav',
    'joguei o fino lisa.wav',
    'ah pronto lisa.wav',
    'ajude lisa.wav',
    'porra foi essa lisa.wav',
    'ahhh lisa.wav',
    'pedro pedro lisa.wav',
    'parei de rir lisa.wav',
    'risa lee.wav',
    'vod-424520327-offset-2578.mp4',
    'aaaah lisa.wav',
    'joao engracado lisa.wav',
    'joao poe a musica ticole.wav',
    'muito chatos lisa.wav',
    'WhatsApp Audio 2019-06-09 at 14.36.06.ogg',
    'AT-cm_469191778.mp4',
    'AT-cm_472137262.mp3',
    'morre pra bot lisa.mp3',
    'alou lisa.mp3',
    'pior 2x lisa.mp3',
    'pizza todo dia lisa.mp3',
    'burgao do faustao lisa.mp3',
    'bem feito lisa.mp3',
    'mariu eh doente lisa.mp3',
    'nojo RJ lisa.mp3',
    'vsf ticole.mp3',
    'mentira lisa.mp3',
    'morri pra muie lisa.mp3',
    'juam eh duente lisa.mp3',
    'ain lisa.mp3',
    'mandar pra pqp lisa.mp3',
    'dar pro chunas lisa.mp3',
    'joao viadagem lisa.mp3',
    'n jogaria lisa.mp3',
    'pokas lisa.mp3',
    'sem palavras lisa.mp3',
    'tirar print ticole.mp3',
    'vc eh moça lisa.mp3',
    'ahh joao lisa.mp3',
    'boludos lisa.mp3',
    'nojo doentes lisa.mp3',
    'mlk doente lisa.mp3',
    'morri lisa.mp3',
    'bem ruins lisa.mp3',
    'eoq lisa.mp3',
    'aha tabom lisa.mp3',
    'klabok lisa.mp3',
    'ãh lisa.mp3',
    'WhatsApp Ptt 2019-06-18 at 12.58.50.ogg',
  ],
  Marina: [
    'Untitled.wmv',
    'rala daqui marina.mp3',
    'oi marina.mp3',
    'suruba marina.mp3',
    'n deixava marina.mp3',
    'pq n baniu marina.mp3',
    'processar marina.mp3',
    'nao painho marina.mp3',
  ],
  Stark: [
    'nova moda stark.wav',
    'ai caceta stark.wav',
    'n eh pra mim stark.mp3',
    'nem fudendo stark.mp3',
    'sem paciencia stark.mp3',
    'cu n perdoado stark.mp3',
    'abrir juntos stark.mp3',
    'ragequit stark.mp3',
    'joao sentando stark.mp3',
    'chingchong stark.mp3',
    'joao pica stark.mp3',
    'miou o game stark.mp3',
    'n necessariamente stark.mp3',
    'merecido stark.mp3',
    'vcs sao ruins stark.mp3',
    'vai chorar stark.mp3',
    'nada a ver stark.mp3',
    'mds stark.mp3',
    'carai stark.mp3',
    'voltei stark.mp3',
    'gosta d muie stark.mp3',
    'n aceitei stark.mp3',
    'lixar chifre stark.mp3',
    'rip sono stark.mp3',
    'para de chora stark.mp3',
    'mata stark.mp3',
    'n sei stark.mp3',
    'nossa vei stark.mp3',
    'agressivo stark.mp3',
    'ficar quieto stark.mp3',
    'pesado stark.mp3',
    'vc eh falso stark.mp3',
    'meu ovo stark.mp3',
    'muta stark.mp3',
    'violento stark.mp3',
    'estragar rola stark.mp3',
  ],
  Reidotiro: [
    'reidotiro vai pro rolezin.mp3',
    'iron farpas reizao.mp3',
    'fralda na boca reizao.mp3',
    'soltando um barro reizao.mp3',
    'maluco ruim reizao.mp3',
    'risada reizao.mp3',
    'botafogo reizao.mp3',
    'meu ovo reizao.mp3',
    'neguinho reizao.mp3',
    'flando serio reizao.mp3',
    'expressar oq penso reizao.mp3',
    'eai drakke reizao.mp3',
    'ficar calado reizao.mp3',
    'coincidencia reizao.mp3',
    'n sou troxa reizao.mp3',
    'drakke admin reizao.mp3',
    'n vou citar nome reizao.mp3',
    'ai ja qro muito reizao.mp3',
    'flw reizao.mp3',
    'como pode isso reizao.mp3',
    'raiva pq morreu reizao.mp3',
    'falei q ia sair.mp3',
    'folgado do krai reizao.mp3',
    'fdp do carai reizao.mp3',
    'barraQ reizao.mp3',
    'eita porra reizao.mp3',
    'caras fdp reizao.mp3',
    'refri reizao.mp3',
    'to em choq reizao.mp3',
    'BK reizao.mp3',
    'agressivo reizao.mp3',
    'ah vsf reizao.mp3',
    'foto bunda reizao.mp3',
    'sou da paz reizao.mp3',
    'que zueira reizao.mp3',
    'qro cantar reizao.mp3',
    'voltei reizao.mp3',
    'tua mae reizao.mp3',
    'como eh bom ser b5 reizao.mp3',
    'ai meu dedinho reizao.mp3',
    'aaaa reizao.mp3',
    'qro jogar reizao.mp3',
    'ah n gouki reizao.mp3',
    'calma reizao.mp3',
    'minha pica reizao.mp3',
    'irresponsabilidade reizao.mp3',
    'orgia reizao.mp3',
    'drakke fdp reizao.mp3',
    'vsf x1 reizao.mp3',
    'vomita porra rei.mp3',
    'n vou falar reizao.mp3',
    'eu qro jogar reizao.mp3',
    'foi ruim reizao.mp3',
    'fdp reizao.mp3',
    'zoa dnv reizao.mp3',
    'eu sarro reizao.mp3',
    'vou zoar reizao.mp3',
    'v1d4 l0k4 reizao.mp3',
    'parar de flar palavrao reizao.mp3',
    'chupar uma piroca reizao.mp3',
    'crl joao cuzao reizao.mp3',
    'explicacao porno gay reizao.mp3',
    'porno gay reizao.mp3',
    'vsf reizao.mp3',
    'fala da irma reizao.mp3',
    'joao lixo reizao.mp3',
    'desculpa reizao.mp3',
    'gouki B5 rei.mp3',
    'cabeça grande reizao.mp3',
    'ctz reizao.mp3',
    'monstrao reizao.mp3',
    'maluco doente reizao.mp3',
    'qm consegue reizao.mp3',
    'falo mto reizao.mp3',
    'hahehe reizao.mp3',
    'eu e gouki zuando reizao.mp3',
    'bugar tb reizao.mp3',
    'se ela corta reizao.mp3',
    'nescau reizao.mp3',
    'corta meu dedo reizao.mp3',
    'dedinho completo reizao.mp3',
    'fretei o shopping reizao.mp3',
    'unha reizao.mp3',
    'rato reizao.mp3',
    'ban perm reizao.mp3',
    'reizao banido 2.mp3',
    'senha rcon reizao.mp3',
    'n sabia reizao.mp3',
    'medo adv reizao.mp3',
    'excluir vcs reizao.mp3',
    'klei a bok reizao.mp3',
    'medo b5 reizao.mp3',
    'o melhor reizao.mp3',
    'ah meu pau reizao.mp3',
    'relogada reizao.mp3',
    'na escola reizao.mp3',
    '3x3 com o reizao.mp3',
    'hehe reizao.mp3',
    'n flo com ele reizao.mp3',
    'n vou flar nada reizao.mp3',
    'qm será reizao.mp3',
    'reizao banido.mp3',
    'excloi joao reizao.mp3',
    'avisei q ia sair reizao.mp3',
  ],
  Mario: [
    'ah meu amigo mariu.wav',
    'crl morri pra muie mariu.wav',
    '34447761104-offset-338.mp4',
    'acabo o time mariu.wav',
    'qse deu bom mariu.wav',
    'vlw tmj mariu.wav',
    'vai dar merda mariu.wav',
    'time voltou mariu.wav',
    'guilherme é retardado mariu.wav',
    'ãh mariu.wav',
    'dedinho mariu.mp3',
    'impressionado mariu.mp3',
    'escovar mariu.mp3',
    'preciso cagar mariu.mp3',
    'vailá mariu.mp3',
    'pq acredito mariu.mp3',
    'vou comer mariu.mp3',
    'mariu baitado.mp3',
    'tnc mariu.mp3',
    'n se aguenta mariu.mp3',
    'chunas goros mariu.mp3',
    'fala mariu.mp3',
    'fui de beise mariu.mp3',
    'xingar macaco mariu.mp3',
    'faz silencio mariu.mp3',
    'startaram mariu.mp3',
    'ahn mariu.mp3',
    'vo ali mariu.mp3',
    'rindo mariu.mp3',
    'ql vai ser mariu.mp3',
    'severus bate em muie mariu.mp3',
    'fumando mariu.mp3',
    'qm entro mariu.mp3',
    'veterinario mariu.mp3',
    'chovendo mariu.mp3',
    'o iron fala mariu.mp3',
    'manda o cara flar mariu.mp3',
  ],
  Guilherme: [
    'a vida cobra gui.wav',
    'to saindo gui.wav',
    'tnc gui.wav',
    'mario eh mongol gui.wav',
    'cala boca gui 2.wav',
    'heh guizao.mp3',
    'agora virei vidente gui.wav',
    'to tiltado gui.wav',
    'guilherme baitado.wav',
    'guizao baitado.mp3',
    'CALA A BOCA GUI.wav',
    'decepção gui.wav',
    'trabalhar psicologico guizao.mp3',
    'NA MTM guizao.mp3',
    'iron dormiu guizao.mp3',
    'bannedts guizao.mp3',
    'ai guizao.mp3',
    'nah guizao.mp3',
    'german responder gui..mp3',
    'to vendo nada gui.mp3',
    'ignorante guizao.mp3',
    'la vem gui.mp3',
    'morri cmo bot gui.mp3',
    'agora tamo gui.mp3',
    'eita porra gui.mp3',
    'oxi porra guizao.mp3',
    'elojob guizao.mp3',
    'ah meu amigo guizao.mp3',
    'ãh guizao.mp3',
    'paia guizao.mp3',
    'como assim guizao.mp3',
    'parente mariu guizao.mp3',
    'lançar braba guizao.mp3',
    'relaxa guizao.mp3',
    'vazar guizao.mp3',
    'joao vale nada guizao.mp3',
    'qm ta pior rayssa.mp3',
    'foi taxado guizao.mp3',
  ],
  Luisão: [
    'amizade luisao.mp3',
    'dormindo luisao.mp3',
    'ingles iron luisao.mp3',
    'cu doce luisao.mp3',
  ],
  premium: [
    'morre fdp prem.wav',
    'ai premium.wav',
    'joao eh chato premium.wav',
    'precisando de internet premium.wav',
    'mlk fdp premium.wav',
    'muta o time premium.wav',
    'para de zicar premium.wav',
    'tnc premium.wav',
    'melekin caiu premium.wav',
    'olha o delay premium.wav',
    'cala a boca mlkwav.wav',
    'batuque premium.wav',
    'lançando disrespect premium.wav',
    'premium_dre.ogg',
    'disrespect fail premium.wav',
    'gouki lançando disrespect.wav',
    'troca de cego premium.wav',
    'bobeira prem.mp3',
    'n vai dar tempo prem.mp3',
    'aaa pqp prem.mp3',
    'que bosta premium.mp3',
    'cara toxico premium.mp3',
    'mijando na cara prem.mp3',
    'parente do iron prem.mp3',
    'se decide premium.mp3',
    'que absurdo premium.mp3',
    'n eh teu parceiro premium.mp3',
    'recalque premium.mp3',
    'caguei prem.mp3',
    'tilta n prem.mp3',
    'prem tiltado.mp3',
    'vcs sao lixo prem.mp3',
    'era audio prem.mp3',
    'ligar pra ticole prem.mp3',
    'cansado no cs prem.mp3',
    'fé premium.mp3',
    'manda zap prem.mp3',
    'ronaldinho prem.mp3',
    'morrendo doido prem.mp3',
    'to tiltado prem.mp3',
    'valeu a pena prem.mp3',
    'iron mia prem.mp3',
    'como assim prem.mp3',
    'no crack prem.mp3',
    'manda zap 2 prem.mp3',
    'qro jogar prem.mp3',
    'n flam nda prem.mp3',
    'bem feito prem.mp3',
    'ain prem.mp3',
    'alo minha piroca prem.mp3',
    'qisso prem.mp3',
    'mete o loco prem.mp3',
    'chego a pizza prem.mp3',
    'mds guizao prem.mp3',
    'vai da bunda prem.mp3',
    'stark no crack prem.mp3',
    'dormido sem essa prem.mp3',
    'nao percebeu prem.mp3',
    'teu kchorro prem.mp3',
    'assoar nariz prem.mp3',
    'n vai demora prem.mp3',
    'tarado prem.mp3',
    'audio novo prem.mp3',
    'chavoso prem.mp3',
    'elvis prem.mp3',
    'chunas ciumes prem.mp3',
    'na moral prem.mp3',
    'e a jaine prem.mp3',
    'full tiltado prem.mp3',
    'assaltar prem.mp3',
    'q brisa prem.mp3',
    'repete prem.mp3',
    'gui vagab prem.mp3',
    'ate muto prem.mp3',
    'geleia prem.mp3',
    'perde o time prem.mp3',
    'arroto prem.mp3',
    'someu prem.mp3',
    'ejacu de vovo prem.mp3',
    'nervoso cinema prem.mp3',
    'barulho mic prem.mp3',
    'anos de xp prem.mp3',
    'ligar ventilador prem.mp3',
    'morre calor prem.mp3',
    'partida esquento prem.mp3',
    'atirando vento prem.mp3',
    'fluzao 9h prem.mp3',
    'iron chato prem.mp3',
    'lagando prem.mp3',
    'recurso prem.mp3',
    'nossa prem.mp3',
    'esporro ao vivo prem.mp3',
    'avassalador prem.mp3',
    'jogo jaja prem.mp3',
    'recebendo bem prem.mp3',
    'vento prem.mp3',
    'assustador prem.mp3',
    'dominando prem.mp3',
    'para de reclamar prem.mp3',
    'pub n prem.mp3',
    'tendi nada prem.mp3',
    'flei pra fazer prem.mp3',
    'vai vai prem.mp3',
    'ele é adm premium.mp3',
    'q 6 tao flando prem.mp3',
    'chunas em shoq prem.mp3',
    'arranhando ingles prem.mp3',
    'ngm vai jogar prem.mp3',
    'sarro prem.mp3',
    'sims heireken prem.mp3',
    'rindo doq prem.mp3',
    'james prem.mp3',
    'desligado prem.mp3',
    'ueba prem.mp3',
    'ixi prem.mp3',
    'german ta doente prem.mp3',
    'risada premium.mp3',
  ],
  João: [
    'hacker joao.mp3',
    'quitar partida joao.wav',
    'paraquedas mae joao.wav',
    'vamo concentrar joao.wav',
    'cheguei joao.wav',
    'crl fdp joao.wav',
    'joao o gado.wav',
    'dar pro chunas joao.wav',
    'jogando ruim joao.wav',
    'qro ver culhao joao.wav',
    'qq tem gadinha joao.wav',
    'troca o nick joao.wav',
    'fiquei perdido joao.wav',
    'vtnc joao.wav',
    'n tem jeito joao.wav',
    'ai joao.wav',
    'krl fui humilhado joao.wav',
    'to chegando joao.wav',
    'boa noite joao.wav',
    'gravando joao.wav',
    'caras engraçados joao.wav',
    'maré virou joao.wav',
    'lembrei do mariu joao.wav',
    'porra lisa joao.wav',
    'AT-cm_457269846.mp4',
    'AT-cm_458219697.mp4',
    'bora bora joão.wav',
    'AT-cm_456077255.mp4',
    'chegou pizza joao.mp3',
    'ladrao joao.mp3',
    'n recebo ordens joao.mp3',
    'seila joao.mp3',
    'rei costinha joao.mp3',
    'drakke bja joao.mp3',
    'mae farofa joao.mp3',
    'silencio joao.mp3',
    'n klabok joao.mp3',
    'ai meu deus joao.mp3',
    'joao exposed.mp3',
    'german pode responder joao.mp3',
    'vc n eh o capitao joao.mp3',
    'qq vai rolar joao.mp3',
    'n ouvir voz joao.mp3',
    'qria ser cego joao.mp3',
    'rola pibe joao.mp3',
    'as ideia joao.mp3',
    'fuck you joao.mp3',
    'acho q eh mentira joao.mp3',
    'chupa gringo joao.mp3',
    'q mundo iron vive joao.mp3',
    'pc do iron travo joao.mp3',
    'tiltou sem jogar joao.mp3',
    'n bote palavras joao.mp3',
    'doença mental joao.mp3',
    'smoke espantado joao.mp3',
    'pessoas alta qldade joao.mp3',
    'vai em clandestino joao.mp3',
    'n eh caridade joao.mp3',
    'o cara n ta on joao.mp3',
    'rei flava merda joao.mp3',
    'humilhação do krl joaomp3.mp3',
    'n tem um elogio joao.mp3',
    'bom d+ joao.mp3',
    'no farpas joao.mp3',
    'tdo dia xingando joao.mp3',
    'aih joao.mp3',
    'call errada joao.mp3',
    'fiquei constrangido joao.mp3',
    'pc quebro joao.mp3',
    'jogo viado joao.mp3',
    'como vc sabe joao.mp3',
    'o cara infarto joao.mp3',
    'mariu pendrive joao.mp3',
    'pateta joao.mp3',
    'assistir joao.mp3',
    'ter qsf joao.mp3',
    'mituzin joao.mp3',
    'meee joao.mp3',
    'dou trem joao.mp3',
    'saludos joao.mp3',
    'chunas inveja joao.mp3',
    'fui chutado joao.mp3',
    'vai tiltar joao.mp3',
    'paula cs joao.mp3',
    'lula livre joao.mp3',
    'irrita morre joao.mp3',
    'chunas sogra joao.mp3',
    'taix ban joao.mp3',
    'é mentira joao.mp3',
    'medo gravar joao.mp3',
    'da po alto joao.mp3',
    'jaine pizza joao.mp3',
    'qm ta ai hj joao.mp3',
    'remix do eh audio joao.mp3',
    'qro jogar joao.mp3',
    'agora eh audio deluxe joao.mp3',
    'vai dar bom joao.mp3',
    'ãh joao.mp3',
    'drakke irma joao.mp3',
  ],
  Marllos: [
    'iron empresario2.wav',
    'qro ganhar dinheiro iron.wav',
    'minha irma iron.wav',
    'abestadobets.wav',
    'ta transmitindo iron.wav',
    'mds iron.mp3',
    'ja era iron.mp3',
    'n me chamaram iron.mp3',
    'perai iron.mp3',
    'meu parente iron.mp3',
    'gouki no time iron.mp3',
    'opa iron.mp3',
    'se acredita iron.mp3',
    'bora testar iron.mp3',
    'ãh iron.mp3',
    'qisso iron.mp3',
    'tdo nosso iron.mp3',
    'alago iron.mp3',
    'james iron.mp3',
    'sdd magrelin iron.mp3',
    'ih lek iron.mp3',
    'sei la iron.mp3',
    'rlx marllindo.mp3',
    'whisky marllindo.mp3',
    'nao po iron.mp3',
    '5 reais iron.mp3',
    'apostar + iron.mp3',
    'e o cu iron.mp3',
    'ferias iron.mp3',
    'to estudando iron.mp3',
    'WhatsApp Ptt 2019-07-13 at 03.40.58.ogg',
    'WhatsApp Ptt 2019-06-10 at 21.02.28.ogg',
  ],
  Mandrakke: [
    'WhatsApp Ptt 2019-06-08 at 11.12.17.ogg',
    'regressiva drakke.mp3',
    'oba mandrakke.mp3',
    'vergonha drakke.mp3',
    'aaa drakke.mp3',
    'jogando alison drakke.mp3',
    'se fude drakkezin.mp3',
    'bora bora drakke.mp3',
    'surra drakke.mp3',
    'fui tua mae drakke.mp3',
    'chunas tiltou drakke.mp3',
    'vo dar rola drakke.mp3',
    'bd flor drakke.mp3',
    'concentra drakke.mp3',
    'sacanagem drakke.mp3',
    'BOA PORRA drakke 2.mp3',
    'arroto drakke.mp3',
    'to comendo drakke.mp3',
    'lag mental drakke.mp3',
    'arrombo drakke.mp3',
    'come drakke.mp3',
    'boa porra drakke.mp3',
    'MDS drakke.mp3',
    'vou sair drakke.mp3',
    'vai vai drakke.mp3',
    'qq isso drakke.mp3',
    'retardados drakke.mp3',
    'vtnc drakke.mp3',
    '6 morrerao tdo drakke.mp3',
    'impossivel audio german drakke.mp3',
    'nossa chunas drakke.mp3',
    'lago blz drakke.mp3',
    'fazendo barulho drakke.mp3',
    'amigo viado drakke.mp3',
    'muito amigo viado drakke.mp3',
    'report drakke.mp3',
    'tiltou ao vivo drakke.mp3',
    'agora é audio drakke.mp3',
    'fudencio drakke.mp3',
    'jogar c amigos drakke.mp3',
    'uuuh drakke.mp3',
    'pegando fogo drakke.mp3',
    'q era audio drakke.mp3',
    'chunas eu e tu drakke.mp3',
    'chupa drakke.mp3',
    'pinou drakke.mp3',
    'kd piranha drakke.mp3',
    'atras paula drakke.mp3',
    'NA piada drakke.mp3',
    'mais gado drakke.mp3',
    'n sabe drakke.mp3',
    'eh isso drakke.mp3',
    'joao costas drakke.mp3',
    'dar o cu drakke.mp3',
    'problema dele drakke.mp3',
    'ae desgraça drakke.mp3',
    'vai fdp drakke.mp3',
    'mariu narnia drakke.mp3',
    'perdeu pra bot drakke.mp3',
    'perdemos drakke.mp3',
    'ta puto hj drakke.mp3',
    'fundo paula drakke.mp3',
    'calma jovem drakke.mp3',
    'melecao drakke.mp3',
    'vesguei drakke.mp3',
    'ahn drakke.mp3',
    'agua com gas drakke.mp3',
    'fui spado drakke.mp3',
    'quase vomitei drakke.mp3',
    'wow drakke.mp3',
    'joao fdp drakke.mp3',
    'desgraça drakke.mp3',
    'tomando surra drakke.mp3',
    'n entendo drakke.mp3',
    'sdds gouki drakke.mp3',
    'lisa me deu drakke.mp3',
  ],
  FL0PES: [
    'fodase o gouki fl0pes.wav',
    'mijou na cara fl0pes.wav',
    'tanto faz fl0pes.mp3',
    'qm eh fl0pes.mp3',
    'caralho fl0pes.mp3',
    'ih carai fl0pes.mp3',
    'ãh fl0pes.mp3',
    'boa partida fl0pes.mp3',
    'q merda fl0pes.mp3',
    'tomara q perca fl0pes.mp3',
    'sabe oq faz fl0pes.mp3',
    'vai perder fl0pes.mp3',
    'ganho sem bugar fl0pes.mp3',
    'xingando gouki fl0pes.mp3',
    'quem fl0pes.mp3',
    'ai mds fl0pes.mp3',
    'praq fl0pes.mp3',
    'olhar isso fl0pes.mp3',
    'qm ta jogando fl0pes.mp3',
    'ai caralho fl0pes.mp3',
    'pq fl0pes.mp3',
  ],
  Paula: [
    'esqueceram da paula.mp3',
    'ihh chunas paula.mp3',
    'paula baitada.mp3',
    'corno paula.mp3',
    'kra bost paula.mp3',
    'falsidade paula.mp3',
    'daria d graça paula.mp3',
  ],
  Datedy: [
    'banhar eh muito boa dately.wav',
    'como 6 sao gostosos dately.wav',
    'já denuncia todo mundo datedy.wav',
    'voltei to comido.wav',
    'que susto datedly.wav',
  ],
  Gorn: [
    'nude do gorn.wav',
    'kchorros gorn.mp3',
    'ja vai gorn.mp3',
    'o gas gorn.mp3',
    'ahn gorn.mp3',
    'maravilhoso gorn.mp3',
    'ta doente gorn.mp3',
    'removido gorn.mp3',
    'que ota gorn.mp3',
    'mto barulho gorn.mp3',
    'ok gorn.mp3',
  ],
};

export default AUDIOS;
